name: Daily User Cleanup

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch: # 手動でも実行可能にする

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 依存関係をインストール
        run: npm install

      - name: Supabase 環境変数を設定
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> $GITHUB_ENV
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV

      - name: 前日作成データの削除バッチを実行
        run: npx ts-node --esm ./batch/index.ts
